apiVersion: apps/v1
kind: Deployment

metadata:
  name: coffee-web
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: coffee-web

  template:
    metadata:
      labels:
        app: coffee-web

    spec:
      containers:
      - name: coffee-web
        image: crqlcoffee2026.azurecr.io/coffee-web:9766be4c2f92632573981beb9b93d52f39b059c4

        imagePullPolicy: Always

        ports:
        - containerPort: 80