apiVersion: apps/v1
kind: Deployment

metadata:
  name: coffee-web
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: coffee-web

  template:
    metadata:
      labels:
        app: coffee-web

    spec:
      containers:
      - name: coffee-web
        image: crqlcoffee2026.azurecr.io/coffee-web:300f23fba77874a395204ca47974ce364fc09632

        imagePullPolicy: Always

        ports:
        - containerPort: 80